config/routes.rb
Rails.application.routes.draw do

  get '/login' => 'session#new'
  post '/session' => 'session#create'
  get '/session' => 'session#show'
  delete '/session' => 'session#destroy'

  root 'users#index'
  resources :users
  scope module: 'users' do
    resources :outfits, :tops, :pants, :shoes
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
    render :new
  end
  # def create
  #   if params[:password] == Rails.application.secrets.secret_password # find_by(password_digest: params[:password])
  #     session[:valid_user] = true
  #     redirect_to '/secret'
  #   else
  #     @error = true
  #     render :new
  #   end
  # end
  # def destroy
  #   reset_session
  #   redirect_to '/login'
  # end
def show
   @user = User.find_by(id: session[:user_id])
   @outfit = @user.outfits
end

  def create
    @user = User.find_by(email: params[:email])

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to '/session'
    else
      @error = true
      render :new
    end
  end
  def destroy
    reset_session
    redirect_to '/login'
  end
  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/views/session/new.html.erb
<div id="maincontainer">
<div class="row">
  <%= image_tag "background.png", class: "col-md-12 background" %>
</div>
  <header>
    <div class="upperHeader">
      <div class="container">
        <ul class="pull-right inline">
          <li class="divider-vertical"></li>
        </ul>
      </div>
    </div>
  </header>
  <div class="login">
      <form method="POST" action = "/session">
        <input type = "email" name = "email" placeholder="Email">
        <input type = "password" name = "password" placeholder="Password">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token() %>"><br>
        <button class="button">Log in</button>
  </form>
  </div>
</div>

app/views/session/show.html.erb
<div id="maincontainer">
  <div class="row">
  <%= image_tag "background.png", class: "col-md-12 background" %>
  </div>
    <header>
    <div class="upperHeader">
      <div class="container">
        <ul class="pull-right inline">
          <form action="/session" method="POST">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token() %>">
            <input type="hidden" name="_method" value="DELETE"> <!-- overriding the method in the form tag -->
            <li><%= link_to "Logout", users_path, class: "invarseColor" %></li>
          </form>
        </ul>
      </div>
    </div>
  </header>
  <%= button_to "WHAT TO WEAR", outfit_path(@outfit), class: "splashlink1", method: :get %>
  <%= button_to "CLOSET", outfits_path, class: "splashlink2", method: :get %>
</div>